################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Clock.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc/Clock.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LaunchPad.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc/LaunchPad.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

board.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/board.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

cpu.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib/cpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

device.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/device.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

driver.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/driver.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

flowcont.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/flowcont.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fpu.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib/fpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fs.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/fs.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

interrupt.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib/interrupt.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

%.obj: ../%.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

netapp.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/netapp.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

netcfg.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/netcfg.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

nonos.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/nonos.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

socket.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/socket.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

spawn.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/spawn.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

spi.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/spi.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sysctl.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib/sysctl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

timer_tick.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p/timer_tick.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ustdlib.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/utils/ustdlib.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

wlan.obj: C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source/wlan.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/CC3100_GetWeather" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/source" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/simplelink/include" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/examples/common" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/cc3100-sdk/platform/msp432p" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/inc" --include_path="C:/Users/Alan/Downloads/tirslk_max_1_00_00/tirslk_max_1_00_00/driverlib" --include_path="C:/ti/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include" --include_path="C:/ti/ccs910/ccs/ccs_base/arm/include/CMSIS" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="$(basename $(<F)).d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


